---
title: "如何制作一幅关系网图"
author: "Curve"
date: '2018-04-24'
slug: ''
tags: []
categories: R
---

```{r include=FALSE}
load("/Users/cvrve/page2/Mine-Map/.RData")
library(dplyr)
library(tidytext)
library(janeaustenr)
library(tidyr)
library(ggraph)
library(igraph)
library(showtext)
library(purrr)
showtext.auto(enable = TRUE)

austen_bigrams <- austen_books() %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2)


bigrams_separated <- austen_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)


bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_graph <- bigram_counts %>%
  filter(n > 20) %>%
  graph_from_data_frame()

kw <- data.frame(index = 1:length(table),
                       chara = unlist(table),
                       stringsAsFactors = FALSE) %>% 
  mutate(len = nchar(chara)) %>% 
  filter(len > 1)
```

近日简单看了下 [Text Mining with R](https://www.tidytextmining.com/ngrams.html)。其中第四章中讲到了如何在文本分析中进行词间关系分析。

```{r}
library(ggraph)
set.seed(2017)

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_bw()
```

便联想到我的一组数据：

```{r}
head(df[c(1,5)])
```

金属伴生是一种常见的现象。比如，从矿山命名中包含着“金—铜矿”，“铅-锌矿”，“铅-锌-银-钼矿”等等说明。不同的金属之间也有着不同的伴生关系，我们该如何呈现出这种关系呢？关系网图是一个很好的选择。

经过一番复杂的处理我们提取到了关键词：

```{r}
head(kw)
```

因为探讨的是二元关系，则对应的数据格式应该是：

```{r}
head(bigram_counts)
```

而我们的 keyword 则是多元的。如，“铜铅锌”，则需要拆分为“铜铅”、“铜锌”，“铅锌”。 

```{r}
para <- unique(kw$len) %>% sort()
kw <- kw %>% 
  split(.$len) %>% 
  map2(para, function(x, y) {
  df <- strsplit(x$chara, "") %>% 
    unlist() %>% 
    matrix(ncol = y, byrow = TRUE) %>% 
    as.data.frame(stringsAsFactors = FALSE) 
  map(as.data.frame(combn(y, 2)), function(z) select(df, z)) %>% 
    map(`names<-`, c("V1", "V2")) %>% 
    reduce(rbind)
}) %>% 
  reduce(rbind) %>% 
  mutate(word1 = ifelse(V1 < V2, V1, V2),
         word2 = ifelse(V1 < V2, V2, V1)) %>% 
  group_by(word1, word2) %>% 
  count(sort = TRUE)
```

经过一系列操作，我们得到了我需要的格式。

```{r}
library(ggraph)
library(igraph)

kw_graph <- kw %>% 
  graph_from_data_frame()

kw_graph
```

作图！

```{r}
ggraph(kw_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_bw()
```


换个主题

```{r}
set.seed(2016)

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(kw_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```

更多细节可以参考 [thomasp85/ggraph: Grammar of Graph Graphics](https://github.com/thomasp85/ggraph)。

## 总结

作图 = 正确的数据格式 + 正确的函数


